// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjD3GRnkT15K3D1ZavzXNlWH4N_3vcqQ',
    appId: '1:175035479397:web:cc8e2f69131c81140f9d8c',
    messagingSenderId: '175035479397',
    projectId: 'shopping-d7a0e',
    authDomain: 'shopping-d7a0e.firebaseapp.com',
    storageBucket: 'shopping-d7a0e.firebasestorage.app',
    measurementId: 'G-T8NRQZYQVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCE4wp7iu1LSmFxj-Zd9q2fmBqXR-vsVg',
    appId: '1:175035479397:android:2bca47223e72a7a40f9d8c',
    messagingSenderId: '175035479397',
    projectId: 'shopping-d7a0e',
    storageBucket: 'shopping-d7a0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMVHREwbXFKGEo7RPQ0s3NEZ8wKf5E2s',
    appId: '1:175035479397:ios:8103c3f26767e3b00f9d8c',
    messagingSenderId: '175035479397',
    projectId: 'shopping-d7a0e',
    storageBucket: 'shopping-d7a0e.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

}